### PR TITLE
Upload&Download Pictures for parkings

### LINKED ISSUE #291: Large pictures makes the app crash on upload
The function in charge of compressing the image before sending it to the database struggle with image of large size. 
This function should be reworked to handle that case

### PR DESCRIPTION
**Pull request by sean-prz**
_Closes #286 #287_
### Implementing the Image Repository into the parking viewmodel.

The parking viewmodels now offers to the UI two new functions :
- `uploadImage` : upload our pictures to our cloud storage and update the parking object to contains the path to that picture.
- `loadSelectedParkingImages` : get all paths stored into the selected parking object and transform them into a list of URL that is passed via a state `selectedParkingImagesUrls` to the UI 

### Modifying the UI
On the details screen the following changes have been made : 
- Reuse Alexandre's code for the image Picker used for profile pictures. 
-  Adds a confirmation screen before uploading the picture.
- The details screen now observe a state of URLS to recompose the list of image each time a new URLS has been transformed.

#### Being able to see pictures of the spot is an important feature that helps the user to locate the spots and easily see if it fits their expectation

-- -
#### Global Code coverage 
image

#### new Code coverage 
- ParkingViewModel at 92%
- UI ParkingDetailsScreen at 83%

-- -

### What's next 
I'll take any suggestions on what needs to be done to polish this feature.
What can be done to improve this new feature : 
- Making a picture clickable to expand it.
- allow user to delete their pictures
- Preventing users from adding more than 5 pictures per spot ?
- allowing User to report pictures
- fix #291

### CODE REVIEW

**Review by matttsss — COMMENTED** [review]
While reviewing I found a small bug... When I tried adding a photo in the ParkingDetailsScreen, the images wouldn't show up... I had to relaunch the app to be able to see the images... Maybe some kind of caching issue?
From the logs, the parking managed to update successfully but the images were not displayed.

**Comment by sean-prz** [comment]
> While reviewing I found a small bug... When I tried adding a photo in the ParkingDetailsScreen, the images wouldn't show up... I had to relaunch the app to be able to see the images... Maybe some kind of caching issue? From the logs, the parking managed to update successfully but the images were not displayed.

Oh.. right, it's because I only fetch the URL's once when arriving on the screen.
We can fix this by observing also the selectedParking, so that when it changes (new pic added) we refetch the URL's 
I've put the selectedParking in the trigger of the launchedEffect an it seems to work now.

**Comment by sean-prz** [comment]
Made some tests to stay at 82%

**Comment by matttsss** [comment]
Right I can now see the images that I upload! However it seems like images too big crash the program 😅

**Comment by sean-prz** [comment]
> Right I can now see the images that I upload! However it seems like images too big crash the program

Well that has to be because of my compressing function, it downscale the images 5% by 5% until the image size is below 300kb, but I guess if at 5% of the original Resolution we're still above 300kb, the edge case is not well handled, let me try to push a fix

**Review by matttsss — APPROVED** [review]
Nice changes, the image load is still a bit slow, could defenitively be worked on for a later PR but it's nice to be able to add pictures!

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt [hunk 1]
```diff
@@ -193,41 +234,38 @@ fun ParkingDetailsScreen(
...
-                                      Modifier.size(170.dp)
-                                          .padding(4.dp)
-                                          .testTag("ParkingImage$index"),
-                                  contentScale = ContentScale.Crop)
+                            items(imagesUrls) { url ->
+                              Image(
+                                  painter = rememberAsyncImagePainter(url),
+                                  contentDescription =
+                                      stringResource(
+                                          R.string.view_profile_screen_profile_picture), // FIXME
```
Comment (Armetiis) [inline app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt:256]: Here you left a fixme. Note that you don't need to use a string resource for the content descriptions

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -88,6 +88,9 @@
     <string name="card_screen_add_review">Add A Review</string>
     <string name="card_screen_report">Report</string>
     <string name="card_screen_no_image">No images for this parking yet</string>
+    <string name="card_screen_confirm_upload">Do you want to add this image to the parking spot ? </string>
+    <string name="card_screen__accept_upload">Yes</string>
+    <string name="card_screen__cancel_upload">No</string>
```
Comment (Armetiis) [inline app/src/main/res/values/strings.xml:93]: We already have general resources for Yes and No, no need to define them again for this specific purpose

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt [hunk 3]
```diff
@@ -69,6 +78,38 @@ fun ParkingDetailsScreen(
...
   val toastMessage = stringResource(R.string.sign_in_to_add_favorites)
+  // === States for the images ===
+  var newParkingImageLocalPath by remember { mutableStateOf("") }
+  val showDialog = remember { mutableStateOf(false) }
+  val imagesUrls by parkingViewModel.selectedParkingImagesUrls.collectAsState()
+  // === === === === === === ===
+
+  LaunchedEffect(Unit, selectedParking) {
+    // On first load of the screen, request the images
+    // This will update the imagesUrls state and trigger a recomposition
```
Comment (Armetiis) [inline app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt:89]: Why do you have a launched effect of unit and selected parking? Isn't just selected parking enough?

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsAlertDialog.kt [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+    onDismiss: () -> Unit,
+    onAccept: () -> Unit,
+    newParkingImageLocalPath: String,
+) {
+  AlertDialog(
+      modifier = Modifier.testTag("parkingDetailsAlertDialog"),
+      onDismissRequest = { onDismiss() },
+      title = { Text(stringResource(R.string.card_screen_confirm_upload)) },
+      text = {
+        Column(
```
Comment (Armetiis) [inline app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsAlertDialog.kt:37]: I don't think you need to wrap the image in a column. You can just add a container color parameter to the Alert Dialog to use surface bright

File: app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt [hunk 5]
```diff
@@ -436,6 +439,67 @@ class ParkingViewModel(
...
+    val destinationPath = "parking/${selectedParking.uid}/${selectedParking.images.size}"
+    imageRepository.uploadImage(
+        context = context,
+        fileUri = imageUri,
+        destinationPath = destinationPath,
+        onSuccess = {
+          selectParking(selectedParking.copy(images = selectedParking.images.plus(destinationPath)))
+          parkingRepository.updateParking(
+              selectedParking,
+              { onSuccess },
```
Comment (Armetiis) [inline app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt:494]: I don't see the purpose of having an onSuccess parameter for now. This is not a problem, we could need it in the fututre. However here it should be `onSucess()`, because `onSuccess` is not a correct syntax for invoking the function

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt [hunk 6]
```diff
@@ -193,41 +234,38 @@ fun ParkingDetailsScreen(
...
-                                          .padding(4.dp)
-                                          .testTag("ParkingImage$index"),
-                                  contentScale = ContentScale.Crop)
+                            items(imagesUrls) { url ->
+                              Image(
+                                  painter = rememberAsyncImagePainter(url),
+                                  contentDescription =
+                                      stringResource(
+                                          R.string.view_profile_screen_profile_picture), // FIXME
+                                  modifier = Modifier.size(100.dp),
```
Comment (Armetiis) [inline app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt:257]: I think here maybe instead of setting the size of the image, we could rather have a fixed height for the lazyrow and have the images fill max height. Honesty not a concern for this PR, as I think the UI could use a bit more work (e.g. when there are images, the add button looks a bit odd hanging there alone). Just taking the chance to mention it and confirm that you agree with me (or not)

**Review by Armetiis — COMMENTED** [review]
Very good job, very nice feature and clean implementation. Your code includes a lots of comments which made it very easy to understand, so thank you for that. I left you some remarks in the code. The one that bothers me the most would be the onSuccess call in the parkingViewModel

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt (hunk 1 above)
Comment (sean-prz) [reply app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt:256]: fixed

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt (hunk 3 above)
Comment (sean-prz) [reply app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt:89]: I'll add a comment to make it clearer !

File: app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt (hunk 5 above)
Comment (sean-prz) [reply app/src/main/java/com/github/se/cyrcle/model/parking/ParkingViewModel.kt:494]: I don't see it either, but it's nice to have a callback for everything that is async in case we ever need it, I'll fix the onSuccess()

File: app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt (hunk 6 above)
Comment (sean-prz) [reply app/src/main/java/com/github/se/cyrcle/ui/parkingDetails/ParkingDetailsScreen.kt:257]: Sure I'll add this to the list of things to be done

**Review by Armetiis — APPROVED** [review]
Thanks for the changes!
